### ISSUE TITLE
Ability to Suggest/Vote on a Data Set

### ISSUE THREAD

**Issue by birdsong** [CityOfPhiladelphia/slash-data#10]
We need to somehow incorporate the OpenDataPhilly nomination/voting page for people to also request a data set, not just submit a right to know form (link to nomination page below)
@gsf @majshehab 

http://opendataphilly.org/opendata/nominate/?sort=rating_score&dir=desc

**Comment by majshehab** [comment]
this can be resolved by changing "Request" to "Nominate" and linking to OpenDataPhilly nomination page @birdsong @gsf

**Comment by timwis** [comment]
@majshehab not sure what you mean..do you mean instead of linking to the RTK process?

I think we also want to note that (a) the voting process will be revamped with the OpenDataPhilly upgrades coming Winter 2014, and (b) we're exploring options with the Law Department to improve the user experience filling out a right to know request form. Do you think that's enough info to warrant a subpage or perhaps a "(Read more)" collapsible?

**Comment by majshehab** [comment]
@timwis my suggestion meant: http://adobe.ly/10vstm9     There was a meeting about this yesterday between @gsf @atogle and @birdsong - I do not think the changes are being implemented
